version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reciclaje_bd
      MYSQL_USER: root
      MYSQL_PASSWORD: tioclaudio
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
